- name: Attaching nfs to VM
  hosts: alpine_servers

  tasks:
  
  - name: Ensure nfs client package is installed
    ansible.builtin.apk:
      name: nfs-utils
      state: latest

  - name: create directory for share if not created
    ansible.builtin.file:
      path: /mnt/nfs-data
      state: directory
      mode: '0755'

  - name: confugure nfs client
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: ns1.gin.com:/data/nfs   /mnt/nfs-data   nfs4    rw,_netdev 0 0
      state: present
    notify:
      - Restart nfs

  handlers:
  - name: Restart nfs
    ansible.builtin.service:
      name: nfs
      enabled: true
      state: restarted
