---
- name: Solving python-dnf problem for almalinux-8
  hosts: alma_servers
  become: yes

  tasks:

  - name: Ensure latest version of openssh is installed
    dnf:
      name: openssh
      state: latest
